- name: Print Hello world
  hosts: servers
  tasks:
  - name: First task
    ansible.builtin.ping:
      
  - name: Second task
    ansible.builtin.debug:
      msg: "Hello webserver you are reachable"



