- name: install and run nginx
  hosts: servers
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: installed

  - name: start service
    ansible.builtin.service:
      name: nginx
      state: started

  - name: stop service
    ansible.builtin.service:
      name: nginx
      state: stopped

  - name: uninstall nginx
    ansible.builtin.package:
      name: nginx
      state: removed