- name: variables
  hosts: servers
  become: yes
  vars:
    course: DevOps with aws
    trainer: Siva
    duration: 120 hr
  tasks:
  - name: print the variables
    vars:
      course: Ansible
    ansible.builtin.debug:
      msg: "Course is {{ course }} , trainer is {{ trainer }} and the duration is {{ duration }}"
  
  - name: print the variables 1
    ansible.builtin.debug:
      msg: "Course is {{ course }}, trainer is {{ trainer }} and the duration is {{ duration }}"


  