- name: testing var prompt
  hosts: servers
  become: yes
  vars_prompt:
  - name: course
    prompt: Please enter course name
    private: no
  - name: duration
    prompt: please enter course duration
  - name: trainer
    prompt: please enter trainer of the course
  
  tasks:
  - name: priting course info
    ansible.builtin.debug:
      msg: "Course is {{ course }}, trainer is {{ trainer }} and the duration is {{ duration }}"