- name: vars from inventory
  hosts: servers
  become: yes 
  tasks:
  - name: print the course information
    ansible.builtin.debug:
      msg: "Course is {{ course }}, trainer is {{ trainer }} and the duration is {{ duration }}"