- name: Testing preferences
  connection: local
  hosts: local
  vars:
    GREET: "Play level"
  vars_files:
    - course.yaml
  vars_prompt:
    - name: GREET
      prompt: Please enter PROMPT varible value
      private: false
  
  tasks:
  - name: Testing task level variables
    vars:
      GREET: "Task level"
    ansible.builtin.debug:
      msg: "Hello from {{ GREET }}"
  