- name: testing var preferences
  hosts: servers
  become: yes
  vars:
    greet: "Play from PLAY level"
  vars_files:
  - vars.yaml
  # vars_prompt:
  # - name: greet
  #   prompt: please enter greet value
  #   private: no
  
  tasks:
  - name: priting testing var preferences
    vars:
      greet: "Play from TASK level"
    ansible.builtin.debug:
      msg: "{{ greet }}"