- name: Testing data types
  hosts: servers
  become: yes
  vars:
    course: "DevOps with AWS" # string
    duration: 120 # int

    topics: # list
    - linux
    - ansible
    - ubuntu
    - terraform
    live: true # bool
    tools: # map (key:value)
      ci: jenkins
      cloud: AWS
      continirazation: Docker
  
  tasks:
  - name: printing course info
    ansible.builtin.debug:
      msg: "Hello I am learning {{ course_name }}, duration: {{ duration }}, topics are: {{ topics }}, is it live?: {{ live }}, tools covered are: {{ tools }}"