- name: create ec2 instance and r53 records
  hosts: local
  connection: local
  vars:
    instance_type: t3.micro
    image_id: ami-0220d79f3f480ecf5
    region: us-east-1
    subnet_id: subnet-02fd2ab01a59476a4
    zone: devopspractice.help
    sg_id: sg-05bdecafe5dc739ee
    instances:
      - mysql
      - backend
      - frontend   
  tasks:
    - name: install AWS python pip libraries
      ansible.builtin.pip:
        name: "{{ item }}"
        executable: pip3.9
      loop:
        - boto3
        - botocore

    - name: start multiple instances
      amazon.aws.ec2_instance:
        name: "{{ item }}"
        instance_type: "{{ instance_type }}"
        image_id: "{{ image_id }}"
        region: "{{ region }}"
        subnet_id: "{{ subnet_id }}"
        security_group: "{{ sg_id }}"
      loop: "{{ instances }}"
      register: ec2_info

    - name: print ec2-info
      ansible.builtin.debug:
        msg: "{{ ec2_info }}"

    - name: print private address
      ansible.builtin.debug:
        msg: "{{ item.instances[0].private_ip_address }}"
      loop: "{{ ec2_info.results }}"
    
    - name: Create route53 records
      amazon.aws.route53:
        state: present
        zone: "{{ zone }}"
        record: "{{ item.item.zone }}"
        type: A
        ttl: 1
        value: "{{ item.instances[0].private_ip_address }}"
        overwrite : true

    - name: Create route53 records with public ip
      amazon.aws.route53:
        state: present
        zone: "{{ zone }}"
        record: "{{ item.item.zone }}"
        type: A
        ttl: 1
        value: "{{ item.instances[0].public_ip_address }}"
        overwrite : true
        when: item.item == frontend

